### ISSUE TITLE
Extending task / result list filtering

### ISSUE THREAD

**Issue by anjavangestel** [IKNL/vantage6-client#20]
Ik wil graag subsets van de task / result lists op kunnen vragen bij de server.

**Tasks**
-	(1) alle door een specifieke user gestuurde tasks kunnen opvragen
-	(2) alle door een specifieke organisatie gestuurde tasks kunnen opvragen
-	(3) alle gestuurde tasks in de collaboratie kunnen opvragen

-	(4) alle tasks met een specifieke name kunnen opvragen
-	(5) alle tasks met een specifiek image kunnen opvragen
-	(6) alle completed of not-completed tasks kunnen opvragen

-	(7) bonus: alle tasks behorende bij 1 specifieke parent task kunnen opvragen (dat je dus alle tasks voor die ene run bij elkaar hebt)

Bij de meesten is de vraag of elke user dit moet mogen (alle tasks van iemand anders opvragen), maar dit kan dan misschien met permissions worden opgelost.

**Results**
Om een result te interpreteren heb je sowieso altijd de task nodig dus opzich hoef je hier niet de hele zelfde lijst. Maar het zou misschien ook nog handig zijn als je tasks/results kan filteren datum dus op:
-	(8) started_at
-	(9) assigned_at
-	(10) finished_at
_(Waar staan deze 3 precies voor eigenlijk?)_

**Overall**
Ik wil ook ‘fields’ kunnen gebruiken bij dit allemaal, dat ik ook nog kan kiezen welke fields ik allemaal wil ipv altijd de hele task terug te krijgen. Nu doe ik vaak fields=[‘id’,’name’]. 

Wat voorbeelden van hoe ik het nu voor me zie:
Filter 3:
```python
client.task.list(collaboration_id=12, fields=['id', 'organization', 'image']) 
>>
[{'id': 521, 'organization': 'IKNL',      'image': 'harbor.vantage6.ai/vantage/vtg.chisq:trolltunga'},
 {'id': 522, 'organization': 'MyStartup', 'image': 'harbor.vantage6.ai/vantage/vtg.coxph:harukas'},
 {'id': 523, 'organization': 'IKNL',      'image': 'harbor.vantage6.ai/algorithms/summary'}]
```
Filter 7:
```python
client.task.list(task_id=500, fields=['id', 'name'])
>>
[{'id': 501, 'name': 'CoxPH'},
 {'id': 502, 'name': 'CoxPH'},
 {'id': 503, 'name': 'CoxPH'},
 {'id': 504, 'name': 'CoxPH'},
 {'id': 505, 'name': 'CoxPH'},
 {'id': 506, 'name': 'CoxPH'},
 {'id': 507, 'name': 'CoxPH'},
 {'id': 508, 'name': 'CoxPH'}]
```

**Comment by frankcorneliusmartin** [comment]
*Client side filtering*
Currently the arguments `field`, `fields`, `filter` and `filters` in the _python-client_ are filters and selection in the client side. 

*Server side filtering* 
A more preffered solution would be your suggestion @bartvanb. Unfortunately this would require considerable effort to implement. However since we're also adding pagination (https://github.com/IKNL/vantage6-server/issues/25) which also changes the queries, this might be the right time to include this as well.

So basically you want to do two things:
(1) You want to make a selection in your table based on a filter. E.g. `task.organization == iknl` 
(2) You want to obtain only specific fields from your records. E.g. from the user table you only want to obtain all usernames and email addresses. 

(In this same query we should include the pagination)

* Remarks on @anjavangestel 
(1) Its not possible to trace back which user send a task. Only the organization from the user.
(2) That would be a selection on the `initiator` field from the `Task`
(3) That would be a selection on `task` field from the `Collaboration`
(4) Maybe a regex on the `name` field from `Task`
(5) Same as (4)
(6) This is already possible on the API and could simply be added to the client
(7) This would be a selection on `parent` from `Task`
(8), (9) and (10) should be able to work with SQL time ranges (https://stackoverflow.com/questions/8895208/sqlalchemy-how-to-filter-date-field)

**Comment by frankcorneliusmartin** [comment]
Started working on extending the server api to support this: 
https://github.com/IKNL/vantage6-server/issues/25 on branch https://github.com/IKNL/vantage6-server/tree/feature/pagination

- [x] extended filtering on results (8), (9) and (10). Also added filtering for on `organization_id`.
- [ ] extend filtering on task (2), (3), (4), (5), (7)

After this is done the `python-client` should be extended to support these filters.

@anjavangestel if you think (1) is really important, we can open a new issue for that?

**Comment by frankcorneliusmartin** [comment]
API is extended to support all cases.

- [ ] update client

@anjavangestel what about use-case (1)?

**Comment by frankcorneliusmartin** [comment]
Client extended in: f64d6a76a8a371f20dcd2fb5d8f84e0fc74b620e

**Comment by bartvanb** [comment]
@anjavangestel @frankcorneliusmartin  Concerning (1) (get all tasks submitted by user X): this requires a new field to be added to the database, as we currently only register which organization starts the task.

We should also consider what would happen if the user A is removed. It would be possible that a new user B is created with the same user id, so that it would *seem* that that user B started those tasks.

**Comment by bartvanb** [comment]
Concerning the last open point (filtering tasks by user_id), there is now a separate issue: IKNL/vantage6-server#93. 
Therefore I am closing this issue
